train_file: ['./data/hateful_memes/train.json']
             
test_file: ['./data/hateful_memes/test_seen.json']
answer_list: './data/hateful_memes/answer_list.json'

vqa_root: './data/hateful_memes/' #train2014/
vg_root: './data/VG/VG_100K/'  #image/

image_res: 384
batch_size_train: 8 
batch_size_test: 8 
k_test: 2

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







