train_file: '/root/autodl-tmp/data/json_down/etrain.json'
val_file: '/root/autodl-tmp/data/json_down/edev_seen.json'                
test_file: '/root/autodl-tmp/data/json_down/etest_seen.json'

image_root: '/root/autodl-tmp/hateful_memes/img/'

image_res: 384
batch_size_train: 16 
batch_size_test: 16 

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







